/-
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
module

public import Mathlib.Algebra.Group.Subgroup.Lattice
public import Mathlib.Algebra.Ring.Defs

/-!
# Additive commutators in a ring

The additive subgroup generated by differences `a * b - b * a`. It need not
be an ideal, so its quotient is used only as an additive group.
-/

set_option warningAsError true

@[expose] public section

namespace Ring

universe u

variable (R : Type u) [Ring R]

/-- The additive subgroup generated by all multiplicative commutators. -/
def additiveCommutators : AddSubgroup R :=
  AddSubgroup.closure {x : R | ∃ a b : R, x = a * b - b * a}

variable {R}

/-- Each difference `a * b - b * a` belongs to the additive commutator subgroup. -/
theorem commutator_mem_additiveCommutators (a b : R) :
    a * b - b * a ∈ additiveCommutators R :=
  AddSubgroup.subset_closure ⟨a, b, rfl⟩

end Ring
