/-
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
module

public import Mathlib.Data.Matrix.Basis
public import Mathlib.LinearAlgebra.Matrix.ElementaryRowOperations
public import Mathlib.Algebra.Group.Subgroup.Finite

/-!
# Elementary units over a ring

The elementary subgroup of the native general linear group is generated by the
off-diagonal units `1 + Matrix.single i j c`. Its construction does not require
commutative coefficients or decidable equality on the coefficient ring.
-/

set_option warningAsError true

@[expose] public section

namespace Matrix.GeneralLinearGroup

universe u v

variable {ι : Type u} [Fintype ι] [DecidableEq ι]
  {R : Type v}

section Ring

variable [Ring R]

private theorem elementaryMatrix_mul (i j : ι) (hij : i ≠ j) (c d : R) :
    (1 + Matrix.single i j c) * (1 + Matrix.single i j d) =
      (1 + Matrix.single i j (c + d) : Matrix ι ι R) := by
  simp only [add_mul, mul_add, one_mul, mul_one]
  rw [Matrix.single_mul_single_of_ne c i j i hij.symm d]
  simp [Matrix.single_add, add_assoc]

/-- The off-diagonal elementary matrix as a unit of the matrix ring. -/
def elementaryUnit (i j : ι) (hij : i ≠ j) (c : R) : GL ι R where
  val := 1 + Matrix.single i j c
  inv := 1 + Matrix.single i j (-c)
  val_inv := by simpa using elementaryMatrix_mul i j hij c (-c)
  inv_val := by simpa using elementaryMatrix_mul i j hij (-c) c

@[simp]
theorem elementaryUnit_val (i j : ι) (hij : i ≠ j) (c : R) :
    ((elementaryUnit i j hij c : GL ι R) : Matrix ι ι R) =
      1 + Matrix.single i j c := rfl

@[simp]
theorem elementaryUnit_zero (i j : ι) (hij : i ≠ j) :
    elementaryUnit (R := R) i j hij 0 = 1 := by
  apply Units.ext
  simp

/-- Multiplication of elementary units at a fixed off-diagonal position is addition
of their coefficients, even when the ring is noncommutative. -/
theorem elementaryUnit_mul_same (i j : ι) (hij : i ≠ j) (c d : R) :
    elementaryUnit i j hij c * elementaryUnit i j hij d =
      elementaryUnit i j hij (c + d) := by
  apply Units.ext
  exact elementaryMatrix_mul i j hij c d

@[simp]
theorem elementaryUnit_inv (i j : ι) (hij : i ≠ j) (c : R) :
    (elementaryUnit i j hij c)⁻¹ = elementaryUnit i j hij (-c) := by
  apply Units.ext
  rfl

/-- The subgroup generated by all off-diagonal elementary units. -/
def elementarySubgroup (ι : Type u) (R : Type v)
    [Fintype ι] [DecidableEq ι] [Ring R] : Subgroup (GL ι R) :=
  Subgroup.closure {g | ∃ i j : ι, ∃ hij : i ≠ j, ∃ c : R,
    g = elementaryUnit i j hij c}

theorem elementaryUnit_mem (i j : ι) (hij : i ≠ j) (c : R) :
    elementaryUnit i j hij c ∈ elementarySubgroup ι R :=
  Subgroup.subset_closure ⟨i, j, hij, c, rfl⟩

/-- Any ordered finite product of elementary generators belongs to the subgroup.
The list product does not impose commutativity on the ambient general linear group. -/
theorem elementary_list_prod_mem (xs : List (GL ι R))
    (hxs : ∀ g ∈ xs, ∃ i j : ι, ∃ hij : i ≠ j, ∃ c : R,
      g = elementaryUnit i j hij c) :
    xs.prod ∈ elementarySubgroup ι R :=
  (elementarySubgroup ι R).list_prod_mem
    (fun g hg ↦ Subgroup.subset_closure (hxs g hg))

/-- No elementary generators exist on an index type with at most one point. -/
theorem elementarySubgroup_eq_bot_of_subsingleton [Subsingleton ι] :
    elementarySubgroup ι R = ⊥ := by
  apply Subgroup.closure_eq_bot_iff.mpr
  rintro g ⟨i, j, hij, c, rfl⟩
  exact (hij (Subsingleton.elim i j)).elim

end Ring

section Commutative

variable [CommRing R]

/-- Compatibility with mathlib's native commutative-ring GL transvection. -/
theorem elementaryUnit_eq_transvection (i j : ι) (hij : i ≠ j) (c : R) :
    elementaryUnit i j hij c = transvection i j hij c := by
  apply Units.ext
  rfl

end Commutative

end Matrix.GeneralLinearGroup
