/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import GeneralLinearGroups.StableGeneralLinear
public import GeneralLinearGroups.ElementaryCommutator
public import GeneralLinearGroups.UnitPivotDiagonalization
public import GeneralLinearGroups.RelativeWhiteheadConsequences
public import Mathlib.GroupTheory.Commutator.Basic
public import Mathlib.GroupTheory.QuotientGroup.Basic
public import Mathlib.GroupTheory.Abelianization.Defs

/-!
# The stable elementary subgroup

The stable elementary subgroup of general linear matrices over a ring is the
directed supremum of the images of finite elementary subgroups. It is defined
without imposing normality on any finite or stable elementary group.
It is perfect in its own right over every ring. As a subgroup of stable general
linear matrices, it is the commutator subgroup; hence the existing quotient
is canonically the abelianization, compatibly with coefficient maps.
-/

set_option warningAsError true

@[expose] public section

namespace Matrix.GeneralLinearGroup

universe u v w

open scoped commutatorElement

@[simp]
theorem finStabilize_elementaryUnit (R : Type u) [Ring R]
    {n m : ℕ} (h : n ≤ m) (i j : Fin n) (hij : i ≠ j) (a : R) :
    finStabilize R h (elementaryUnit i j hij a) =
      elementaryUnit (Fin.castLE h i) (Fin.castLE h j)
        (fun eq => hij (Fin.castLE_injective h eq)) a := by
  change reindexEquiv R (finBlockEquiv h)
    (stabilize (Y := Fin (m - n)) (elementaryUnit i j hij a)) =
      elementaryUnit (Fin.castLE h i) (Fin.castLE h j)
        (fun eq => hij (Fin.castLE_injective h eq)) a
  simp only [stabilize_elementaryUnit, reindexEquiv_elementaryUnit,
    finBlockEquiv_inl]

/-- Initial-segment stabilization sends a finite elementary group into the
elementary group in the larger rank. -/
theorem finStabilize_elementarySubgroup_le (R : Type u) [Ring R]
    {n m : ℕ} (h : n ≤ m) :
    (elementarySubgroup (Fin n) R).map (finStabilize R h) ≤
      elementarySubgroup (Fin m) R := by
  intro g hg
  obtain ⟨e, he, rfl⟩ := hg
  exact reindexEquiv_mem_elementarySubgroup (finBlockEquiv h)
    (stabilize_elementarySubgroup_le (Subgroup.mem_map_of_mem _ he))

/-- The subgroup of stable general linear matrices generated by finite-rank
elementary matrices, as an increasing union of finite elementary images. -/
noncomputable def stableElementarySubgroup (R : Type u) [Ring R] : Subgroup (StableGL R) :=
  ⨆ n : ℕ, (elementarySubgroup (Fin n) R).map (StableGL.stage R n)

/-- Every element of a finite elementary group lies in stable elementary GL. -/
theorem elementary_stage_le (R : Type u) [Ring R] (n : ℕ) :
    (elementarySubgroup (Fin n) R).map (StableGL.stage R n) ≤
      stableElementarySubgroup R :=
  le_iSup (fun n : ℕ => (elementarySubgroup (Fin n) R).map (StableGL.stage R n)) n

theorem elementary_stage_mono (R : Type u) [Ring R]
    {n m : ℕ} (h : n ≤ m) :
    (elementarySubgroup (Fin n) R).map (StableGL.stage R n) ≤
      (elementarySubgroup (Fin m) R).map (StableGL.stage R m) := by
  intro g hg
  obtain ⟨e, he, rfl⟩ := hg
  refine ⟨finStabilize R h e,
    finStabilize_elementarySubgroup_le R h (Subgroup.mem_map_of_mem _ he), ?_⟩
  exact StableGL.stage_finStabilize R h e

/-- The finite elementary images form a directed family of subgroups. -/
theorem elementary_stage_directed (R : Type u) [Ring R] :
    Directed (· ≤ ·) (fun n : ℕ =>
      (elementarySubgroup (Fin n) R).map (StableGL.stage R n)) := by
  intro n m
  exact ⟨max n m, elementary_stage_mono R (le_max_left n m),
    elementary_stage_mono R (le_max_right n m)⟩

/-- Membership in stable elementary GL is witnessed by one finite elementary
matrix, not merely by an arbitrary product of unrelated stable elements. -/
theorem mem_stableElementarySubgroup_iff (R : Type u) [Ring R]
    (g : StableGL R) :
    g ∈ stableElementarySubgroup R ↔
      ∃ n : ℕ, ∃ e : elementarySubgroup (Fin n) R, StableGL.stage R n e = g := by
  rw [stableElementarySubgroup,
    Subgroup.mem_iSup_of_directed (elementary_stage_directed R)]
  constructor
  · rintro ⟨n, ⟨e, he, rfl⟩⟩
    exact ⟨n, ⟨e, he⟩, rfl⟩
  · rintro ⟨n, ⟨e, he⟩, rfl⟩
    exact ⟨n, ⟨e, he, rfl⟩⟩

/-- The stable image of any elementary generator belongs to the stable
elementary subgroup. -/
theorem elementaryUnit_mem_stableElementarySubgroup (R : Type u) [Ring R]
    (n : ℕ) (i j : Fin n) (hij : i ≠ j) (a : R) :
    StableGL.stage R n (elementaryUnit i j hij a) ∈
      stableElementarySubgroup R :=
  elementary_stage_le R n
    (Subgroup.mem_map_of_mem _ (elementaryUnit_mem i j hij a))

/-- Stable elementary GL is precisely the ordinary subgroup generated by
the finite elementary generators, without taking a normal closure. -/
theorem stableElementarySubgroup_eq_closure (R : Type u) [Ring R] :
    stableElementarySubgroup R =
      Subgroup.closure {g : StableGL R | ∃ (n : ℕ) (i j : Fin n)
        (hij : i ≠ j) (a : R), g = StableGL.stage R n (elementaryUnit i j hij a)} := by
  apply le_antisymm
  · refine iSup_le fun n => ?_
    apply Subgroup.map_le_iff_le_comap.mpr
    change Subgroup.closure _ ≤ _
    apply (Subgroup.closure_le _).mpr
    rintro _ ⟨i, j, hij, a, rfl⟩
    exact Subgroup.subset_closure ⟨n, i, j, hij, a, rfl⟩
  · apply (Subgroup.closure_le _).mpr
    rintro _ ⟨n, i, j, hij, a, rfl⟩
    exact elementaryUnit_mem_stableElementarySubgroup R n i j hij a

/-- Coefficient maps carry stable elementary matrices into stable elementary
matrices over the target ring. -/
theorem StableGL.map_elementarySubgroup_le
    {R : Type u} {S : Type v} [Ring R] [Ring S] (f : R →+* S) :
    (stableElementarySubgroup R).map (StableGL.map f) ≤
      stableElementarySubgroup S := by
  rw [stableElementarySubgroup_eq_closure R]
  apply Subgroup.map_le_iff_le_comap.mpr
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨n, i, j, hij, a, rfl⟩
  change StableGL.map f (StableGL.stage R n (elementaryUnit i j hij a)) ∈
    stableElementarySubgroup S
  rw [StableGL.map_stage, mapRingHom_elementaryUnit]
  exact elementaryUnit_mem_stableElementarySubgroup S n i j hij (f a)

/-- Coefficient mapping restricted to the stable elementary subgroups. -/
noncomputable def StableGL.mapElementary
    {R : Type u} {S : Type v} [Ring R] [Ring S] (f : R →+* S) :
    stableElementarySubgroup R →* stableElementarySubgroup S where
  toFun e := ⟨StableGL.map f e.1,
    StableGL.map_elementarySubgroup_le f (Subgroup.mem_map_of_mem _ e.2)⟩
  map_one' := Subtype.ext (map_one (StableGL.map f))
  map_mul' _ _ := Subtype.ext (map_mul (StableGL.map f) _ _)

@[simp]
theorem StableGL.mapElementary_coe
    {R : Type u} {S : Type v} [Ring R] [Ring S]
    (f : R →+* S) (e : stableElementarySubgroup R) :
    ((StableGL.mapElementary f e : stableElementarySubgroup S) : StableGL S) =
      StableGL.map f (e : StableGL R) := rfl

@[simp]
theorem StableGL.mapElementary_id (R : Type u) [Ring R] :
    StableGL.mapElementary (RingHom.id R) =
      MonoidHom.id (stableElementarySubgroup R) := by
  ext e
  simp

@[simp]
theorem StableGL.mapElementary_comp
    {R : Type u} {S : Type v} {T : Type w}
    [Ring R] [Ring S] [Ring T] (f : R →+* S) (g : S →+* T) :
    StableGL.mapElementary (g.comp f) =
      (StableGL.mapElementary g).comp (StableGL.mapElementary f) := by
  ext e
  simp

/-- A finite commutator becomes elementary after doubling the rank. -/
theorem finStabilize_commutator_mem_elementarySubgroup (R : Type u) [Ring R]
    (n : ℕ) (g h : GL (Fin n) R) :
    finStabilize R (Nat.le_add_right n n) ⁅g, h⁆ ∈
      elementarySubgroup (Fin (n + n)) R := by
  have hdouble : stabilize (Y := Fin n) ⁅g, h⁆ ∈
      elementarySubgroup (Fin n ⊕ Fin n) R := by
    rw [commutatorElement_def, stabilize_commutator_eq_blockDiagonalUnit_mul]
    exact (elementarySubgroup (Fin n ⊕ Fin n) R).mul_mem
      ((elementarySubgroup (Fin n ⊕ Fin n) R).mul_mem
        (blockDiagonalUnit_mem_elementarySubgroup g)
        (blockDiagonalUnit_mem_elementarySubgroup h))
      (blockDiagonalUnit_mem_elementarySubgroup ((h * g)⁻¹))
  have hsame : stabilize (Y := Fin (n + n - n)) ⁅g, h⁆ ∈
      elementarySubgroup (Fin n ⊕ Fin (n + n - n)) R := by
    have hindex : n + n - n = n := by omega
    rw [hindex]
    exact hdouble
  exact reindexEquiv_mem_elementarySubgroup (finBlockEquiv (Nat.le_add_right n n)) hsame

/-- Over any ring, stable elementary GL equals the commutator subgroup of
stable GL. No finite-rank ambient normality is assumed. -/
theorem stableElementarySubgroup_eq_commutator (R : Type u) [Ring R] :
    stableElementarySubgroup R = _root_.commutator (StableGL R) := by
  apply le_antisymm
  · rw [stableElementarySubgroup_eq_closure]
    apply (Subgroup.closure_le _).mpr
    rintro _ ⟨n, i, j, hij, a, rfl⟩
    let rank := max n 3
    let larger : n ≤ rank := le_max_left n 3
    have hthree : 3 ≤ Fintype.card (Fin rank) := by
      simp [rank]
    have hperfect : Group.IsPerfect (elementarySubgroup (Fin rank) R) :=
      elementarySubgroup_isPerfect_of_three_le_card hthree
    let e : elementarySubgroup (Fin rank) R :=
      ⟨finStabilize R larger (elementaryUnit i j hij a),
        finStabilize_elementarySubgroup_le R larger
          (Subgroup.mem_map_of_mem _ (elementaryUnit_mem i j hij a))⟩
    let inclusion : elementarySubgroup (Fin rank) R →* StableGL R :=
      (StableGL.stage R rank).comp (elementarySubgroup (Fin rank) R).subtype
    have he : inclusion e ∈
        (_root_.commutator (elementarySubgroup (Fin rank) R)).map inclusion :=
      Subgroup.mem_map_of_mem inclusion
        (Group.IsPerfect.mem_commutator (hP := hperfect))
    have hle :
        (_root_.commutator (elementarySubgroup (Fin rank) R)).map inclusion ≤
          _root_.commutator (StableGL R) := by
      rw [map_commutator_eq, commutator_def]
      exact Subgroup.commutator_mono le_top le_top
    have hmem := hle he
    change StableGL.stage R rank
      (finStabilize R larger (elementaryUnit i j hij a)) ∈
        _root_.commutator (StableGL R) at hmem
    change StableGL.stage R n (elementaryUnit i j hij a) ∈
      _root_.commutator (StableGL R)
    rw [← StableGL.stage_finStabilize R larger]
    exact hmem
  · rw [commutator_def]
    apply Subgroup.commutator_le.mpr
    intro g _ h _
    obtain ⟨n, x, rfl⟩ := StableGL.exists_stage R g
    obtain ⟨m, y, rfl⟩ := StableGL.exists_stage R h
    let rank := max n m
    let left : n ≤ rank := le_max_left n m
    let right : m ≤ rank := le_max_right n m
    let x' := finStabilize R left x
    let y' := finStabilize R right y
    have he : finStabilize R (Nat.le_add_right rank rank) ⁅x', y'⁆ ∈
        elementarySubgroup (Fin (rank + rank)) R :=
      finStabilize_commutator_mem_elementarySubgroup R rank x' y'
    have hmem : StableGL.stage R (rank + rank)
        (finStabilize R (Nat.le_add_right rank rank) ⁅x', y'⁆) ∈
          stableElementarySubgroup R :=
      elementary_stage_le R (rank + rank) (Subgroup.mem_map_of_mem _ he)
    simpa only [StableGL.stage_finStabilize, map_commutatorElement, x', y']
      using hmem

/-- The stable elementary subgroup is perfect as a group in its own right. -/
instance stableElementarySubgroup_isPerfect (R : Type u) [Ring R] :
    Group.IsPerfect (stableElementarySubgroup R) := by
  apply Subgroup.isPerfect_iff.mpr
  apply le_antisymm
  · exact Subgroup.commutator_le_of_le le_rfl le_rfl
  · change (⨆ n : ℕ, (elementarySubgroup (Fin n) R).map (StableGL.stage R n)) ≤
      ⁅stableElementarySubgroup R, stableElementarySubgroup R⁆
    refine iSup_le fun n => ?_
    let rank := max n 3
    have hthree : 3 ≤ Fintype.card (Fin rank) := by
      simp [rank]
    let : Group.IsPerfect (elementarySubgroup (Fin rank) R) :=
      elementarySubgroup_isPerfect_of_three_le_card hthree
    have hperfect : Group.IsPerfect
        ((elementarySubgroup (Fin rank) R).map (StableGL.stage R rank)) :=
      Group.IsPerfect.map (StableGL.stage R rank)
    calc
      (elementarySubgroup (Fin n) R).map (StableGL.stage R n) ≤
          (elementarySubgroup (Fin rank) R).map (StableGL.stage R rank) :=
        elementary_stage_mono R (le_max_left n 3)
      _ = ⁅(elementarySubgroup (Fin rank) R).map (StableGL.stage R rank),
          (elementarySubgroup (Fin rank) R).map (StableGL.stage R rank)⁆ :=
        (Subgroup.isPerfect_iff.mp hperfect).symm
      _ ≤ ⁅stableElementarySubgroup R, stableElementarySubgroup R⁆ :=
        Subgroup.commutator_mono (elementary_stage_le R rank)
          (elementary_stage_le R rank)

/-- Stable elementary GL is normal as a consequence of the commutator equality. -/
instance stableElementarySubgroup_normal (R : Type u) [Ring R] :
    (stableElementarySubgroup R).Normal := by
  rw [stableElementarySubgroup_eq_commutator]
  infer_instance

/-- The quotient of stable GL by the stable elementary subgroup is abelian. -/
theorem stableElementary_quotient_mul_comm (R : Type u) [Ring R]
    (g h : StableGL R ⧸ stableElementarySubgroup R) : g * h = h * g := by
  have hle : _root_.commutator (StableGL R) ≤ stableElementarySubgroup R := by
    rw [stableElementarySubgroup_eq_commutator]
  have hcomm : IsMulCommutative (StableGL R ⧸ stableElementarySubgroup R) :=
    (Subgroup.Normal.quotient_commutative_iff_commutator_le).2 hle
  exact hcomm.is_comm.comm g h

/-- The existing quotient group by stable elementary matrices is commutative. -/
noncomputable instance stableElementaryQuotientCommGroup (R : Type u) [Ring R] :
    CommGroup (StableGL R ⧸ stableElementarySubgroup R) where
  __ := QuotientGroup.Quotient.group _
  mul_comm := stableElementary_quotient_mul_comm R

/-- The quotient by stable elementary matrices is canonically the abelianization
of stable general linear matrices. -/
noncomputable def stableElementaryAbelianizationEquiv (R : Type u) [Ring R] :
    (StableGL R ⧸ stableElementarySubgroup R) ≃* Abelianization (StableGL R) :=
  QuotientGroup.quotientMulEquivOfEq (stableElementarySubgroup_eq_commutator R)

@[simp]
theorem stableElementaryAbelianizationEquiv_mk (R : Type u) [Ring R] (g : StableGL R) :
    stableElementaryAbelianizationEquiv R
      (QuotientGroup.mk' (stableElementarySubgroup R) g) = Abelianization.of g := by
  exact QuotientGroup.quotientMulEquivOfEq_mk
    (stableElementarySubgroup_eq_commutator R) g

@[simp]
theorem stableElementaryAbelianizationEquiv_symm_of (R : Type u) [Ring R]
    (g : StableGL R) :
    (stableElementaryAbelianizationEquiv R).symm (Abelianization.of g) =
      QuotientGroup.mk' (stableElementarySubgroup R) g := by
  apply (stableElementaryAbelianizationEquiv R).injective
  change Abelianization.of g =
    stableElementaryAbelianizationEquiv R
      (QuotientGroup.mk' (stableElementarySubgroup R) g)
  exact (stableElementaryAbelianizationEquiv_mk R g).symm

/-- The abelianization lift agrees with the original map on representatives
of the stable elementary quotient. -/
theorem stableElementaryAbelianizationEquiv_lift_comp_mk (R : Type u) [Ring R]
    {A : Type w} [CommGroup A] (f : StableGL R →* A) :
    ((Abelianization.lift f).comp
      (stableElementaryAbelianizationEquiv R).toMonoidHom).comp
        (QuotientGroup.mk' (stableElementarySubgroup R)) = f := by
  apply MonoidHom.ext
  intro g
  change (Abelianization.lift f)
    (stableElementaryAbelianizationEquiv R
      (QuotientGroup.mk' (stableElementarySubgroup R) g)) = f g
  rw [stableElementaryAbelianizationEquiv_mk, Abelianization.lift_apply_of]

/-- The canonical equivalence commutes with change of coefficient rings. -/
theorem stableElementaryAbelianizationEquiv_map {R : Type u} {S : Type v}
    [Ring R] [Ring S] (f : R →+* S)
    (q : StableGL R ⧸ stableElementarySubgroup R) :
    stableElementaryAbelianizationEquiv S
      (QuotientGroup.map (stableElementarySubgroup R)
        (stableElementarySubgroup S) (StableGL.map f)
        ((Subgroup.map_le_iff_le_comap).mp (StableGL.map_elementarySubgroup_le f)) q) =
      Abelianization.map (StableGL.map f)
        (stableElementaryAbelianizationEquiv R q) := by
  refine QuotientGroup.induction_on q ?_
  intro g
  rw [QuotientGroup.map_mk]
  change stableElementaryAbelianizationEquiv S
      (QuotientGroup.mk' (stableElementarySubgroup S) (StableGL.map f g)) =
    Abelianization.map (StableGL.map f)
      (stableElementaryAbelianizationEquiv R
        (QuotientGroup.mk' (stableElementarySubgroup R) g))
  rw [stableElementaryAbelianizationEquiv_mk,
    stableElementaryAbelianizationEquiv_mk, Abelianization.map_of]

end Matrix.GeneralLinearGroup
